language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
      addons:
        apt:
          packages:
          - cmake
          - clang
          - llvm
          - libfuse-dev
          - libfuse2
          - somerandompackage
    - os: osx
      sudo: false
      osx_image: xcode8.2
      compiler: clang
      before_install:
        - brew update
        - brew cask install osxfuse

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email: false