sudo: required
dist: xenial

addons:
  apt:
    packages:
    # install toolchains
    - cmake
    - gcc
    - g++
    - clang
    - llvm
    # install dependencies
    - libfuse-dev
    - libfuse2

language: cpp

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make


notifications:
  email: false