language: cpp
sudo: false

cache: ccache

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - llvm-3.8
            - libfuse-dev
            - libfuse2
    - os: osx
      allow_failures: true
      osx_image: xcode8.2
      compiler: clang
      before_install:
        - brew update
        - brew cask install osxfuse

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email: false