language: cpp
sudo: false

cache: ccache

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - llvm-3.8
            - libfuse-dev
            - libfuse2
            - valgrind
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      before_install:
        - brew update
        - brew cask install osxfuse
        - brew install valgrind

before_script:
  - mkdir fusecam
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - valgrind --leak-check=yes ./Dummy ../fusecam
  - cd ../fusecam
  - echo 1 > trigger1
  - cat trigger 1
  - rm trigger 1
  - cd ..
  - fusermount -z -u fusecam

notifications:
  email: false