language: cpp
sudo: false

cache: ccache

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
          - libfuse-dev
          - libfuse2
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      before_install:
        - brew update
        - brew cask install osxfuse

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email: false